project:
  type: website
  output-dir: _site
  post-render:
    - add-extra-files.R

website:
  title: "Interactive Data Lessons"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - intro-r.qmd
      - vectors.qmd
      - dplyr.qmd
      - ggplot.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

